apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: cicd-app
          image: 788133893166.dkr.ecr.eu-central-1.amazonaws.com/cicd-app:latest
          ports:
            - containerPort: 8080
