apiVersion: v1
kind: Service
metadata:
  name: cicd-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cicd
